// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using rBR.Scraper.Data.Internal.Context;

#nullable disable

namespace rBR.Scraper.Data.Internal.Migrations
{
    [DbContext(typeof(rBRScraperContext))]
    [Migration("20250506135943_V_1_0_0")]
    partial class V_1_0_0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.CommonScraper", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("sysdate()");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(9);

                    b.Property<string>("DataId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnOrder(7);

                    b.Property<string>("Modified")
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(2);

                    b.Property<string>("ModifiedAt")
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(10);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(8);

                    b.Property<string>("Removed")
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(3);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("DataId")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CommonScrapers", (string)null);
                });

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.InstagramProfileScraperDataset", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("sysdate()");

                    b.Property<string>("DataId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(5);

                    b.Property<int?>("FollowersCount")
                        .HasColumnType("int")
                        .HasColumnOrder(10);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnOrder(9);

                    b.Property<string>("FullObjectData")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("FullObject")
                        .HasColumnOrder(14);

                    b.Property<string>("InputUrl")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnOrder(7);

                    b.Property<string>("Modified")
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(2);

                    b.Property<string>("Removed")
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(3);

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(13);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(12);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnOrder(6);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnOrder(8);

                    b.Property<ulong?>("Verified")
                        .HasColumnType("bit")
                        .HasColumnOrder(11);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RunId");

                    b.HasIndex("UserName", "InputUrl", "DataId", "RunId")
                        .IsUnique();

                    b.ToTable("InstagramProfileScraperDatasets", (string)null);
                });

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.InstagramScraperDataset", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("sysdate()");

                    b.Property<string>("DataId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("FullObjectData")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("FullObject")
                        .HasColumnOrder(11);

                    b.Property<string>("InputUrl")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnOrder(7);

                    b.Property<string>("InstagramProfileId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(10);

                    b.Property<string>("Modified")
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(2);

                    b.Property<string>("Removed")
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(3);

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(9);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.Property<string>("Timestamp")
                        .IsRequired()
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(8);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(300)")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("InstagramProfileId");

                    b.HasIndex("RunId");

                    b.ToTable("InstagramScraperDatasets", (string)null);
                });

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.ScraperRun", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(0);

                    b.Property<string>("Created")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(1)
                        .HasDefaultValueSql("sysdate()");

                    b.Property<string>("DataId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(5);

                    b.Property<string>("DataStatus")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(6);

                    b.Property<string>("DatasetId")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnOrder(7);

                    b.Property<string>("FinishedAt")
                        .IsRequired()
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(9);

                    b.Property<ulong>("Imported")
                        .HasColumnType("bit")
                        .HasColumnOrder(10);

                    b.Property<string>("ImportingError")
                        .HasColumnType("text")
                        .HasColumnOrder(11);

                    b.Property<string>("Modified")
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(2);

                    b.Property<string>("Removed")
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(3);

                    b.Property<string>("ScraperId")
                        .IsRequired()
                        .HasColumnType("varchar(36)")
                        .HasColumnOrder(12);

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("varchar(33)")
                        .HasColumnOrder(8);

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnOrder(4);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ScraperId");

                    b.HasIndex("DataId", "DatasetId")
                        .IsUnique();

                    b.ToTable("ScrapersRuns", (string)null);
                });

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.InstagramProfileScraperDataset", b =>
                {
                    b.HasOne("rBR.BaseLibraries.Domain.Entity.ScraperRun", "Run")
                        .WithMany("InstagramProfiles")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.InstagramScraperDataset", b =>
                {
                    b.HasOne("rBR.BaseLibraries.Domain.Entity.InstagramProfileScraperDataset", "InstagramProfile")
                        .WithMany("InstagramPosts")
                        .HasForeignKey("InstagramProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("rBR.BaseLibraries.Domain.Entity.ScraperRun", "Run")
                        .WithMany("InstagramPosts")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("InstagramProfile");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.ScraperRun", b =>
                {
                    b.HasOne("rBR.BaseLibraries.Domain.Entity.CommonScraper", "Scraper")
                        .WithMany("Runs")
                        .HasForeignKey("ScraperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scraper");
                });

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.CommonScraper", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.InstagramProfileScraperDataset", b =>
                {
                    b.Navigation("InstagramPosts");
                });

            modelBuilder.Entity("rBR.BaseLibraries.Domain.Entity.ScraperRun", b =>
                {
                    b.Navigation("InstagramPosts");

                    b.Navigation("InstagramProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
