//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rBR.Scraper.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusinessErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusinessErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rBR.Scraper.Domain.Properties.BusinessErrorMessages", typeof(BusinessErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested dataset is unavailable (APIFY):.
        /// </summary>
        public static string ApiFyDatasetUnavailable {
            get {
                return ResourceManager.GetString("ApiFyDatasetUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |The request to APIFY failed - Exception: {0}.
        /// </summary>
        public static string ApiFyFailedRequest {
            get {
                return ResourceManager.GetString("ApiFyFailedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |The user [{0}] couldn&apos;t be created:.
        /// </summary>
        public static string ErrorCreatingUser {
            get {
                return ResourceManager.GetString("ErrorCreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Scraper ({0}) is not active. Importing is not possible..
        /// </summary>
        public static string InactiveScraperForImport {
            get {
                return ResourceManager.GetString("InactiveScraperForImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given Dataset/Scraper, of type {0} is invalid for this type of Scraper, of type {1}..
        /// </summary>
        public static string InvalidDatasetForScraper {
            get {
                return ResourceManager.GetString("InvalidDatasetForScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Instagram Profile Datasets were imported for the Instagram Datasets that were intended to be imported; no records were imported..
        /// </summary>
        public static string MissingInstagramProfileForInstagram {
            get {
                return ResourceManager.GetString("MissingInstagramProfileForInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available Scraper Runs for importing Datasets (all already imported or there are errors in the previous attempted importing processes)..
        /// </summary>
        public static string NotAvailableRunsException {
            get {
                return ResourceManager.GetString("NotAvailableRunsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |The object of type [{0}] with Id [{1}] was not found..
        /// </summary>
        public static string ObjectIdNotFoundError {
            get {
                return ResourceManager.GetString("ObjectIdNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |The user for the UserName [{0}] was not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
